### PR TITLE
[Reviewer: Rob] Move to 1.7

### PR DESCRIPTION
**Pull request by eleanor-merry**
Required to build on 14.04. The changes are just to take 1.7 instead of 1.6

### CODE REVIEW

**Comment by bossmc** [comment]
Assuming Graeme is happy with this, I vote we just push it into master as that's what we'd do elsewhere for upstream code drops (and then rebase any local changes if there are any).

**Comment by rkday-pro** [comment]
I don't think there's a lot of value in reviewing the code - if the UTs compile and run without problems, let's just push it to master.

**Comment by eleanor-merry** [comment]
Assigning to you (@AlexHockey) as you've agreed to fix up the references

**Comment by AlexHockey** [comment]
As discussed, I am planning to just fast-forward master, so am closing this PR.

**Pull request closed without merging**
